// 키 코드를 읽기 쉬운 형태로 변환하는 매핑
export const codeToKey: Record<string, string> = {
  // 숫자 키
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Digit0: "0",

  // 문자 키
  KeyA: "a",
  KeyB: "b",
  KeyC: "c",
  // ... 다른 알파벳들도 같은 패턴
  keyD: "d",
  keyE: "e",
  keyF: "f",
  keyG: "g",
  keyH: "h",
  keyI: "i",
  keyJ: "j",
  keyK: "k",
  keyL: "l",
  keyM: "m",
  keyN: "n",
  keyO: "o",
  keyP: "p",
  keyQ: "q",
  keyR: "r",
  keyS: "s",
  keyT: "t",
  keyU: "u",
  keyV: "v",
  keyW: "w",
  keyX: "x",
  keyY: "y",
  KeyZ: "z",

  // 특수 키
  Space: "space",
  ArrowUp: "↑",
  ArrowDown: "↓",
  ArrowLeft: "←",
  ArrowRight: "→",
  Enter: "enter",
  Escape: "esc",
  Tab: "tab",
  Backspace: "backspace",
  Delete: "delete",
  Home: "home",
  End: "end",
  PageUp: "pageup",
  PageDown: "pagedown",

  // 기능 키
  F1: "f1",
  F2: "f2",
  // ... 다른 F 키들
  F3: "f3",
  F4: "f4",
  F5: "f5",
  F6: "f6",
  F7: "f7",
  F8: "f8",
  F9: "f9",
  F10: "f10",
  F11: "f11",
  F12: "f12",

  // 기타
  Minus: "-",
  Equal: "=",
  BracketLeft: "[",
  BracketRight: "]",
  Backslash: "\\",
  Backquote: "₩",
  Semicolon: ";",
  Quote: " ' ",
  Comma: " , ",
  Period: " . ",
  Slash: "/",
};
